GET http://localhost:5000/api/user

###

GET http://localhost:5000/api/user-role

###

GET http://localhost:5000/api/user-status

###

GET http://localhost:5000/api/user/:id
Content-Type: application/json

{
    "_id": "6081712183c493590a981f42"
}

###

GET http://localhost:5000/api/posts/user
Content-Type: application/json

{
    "_id": "6081712f83c493590a981f43"
}

###

GET http://localhost:5000/api/posts

###

GET http://localhost:5000/api/post/:id
Content-Type: application/json

{
    "_id": "608177bbcafa6a64c24b386a",
    "text": "Hello world"
}

###

POST http://localhost:5000/api/register 
Content-Type: application/json

{
    "userName": "test6",
    "firstName": "Förnamn",
    "lastName": "Efternamnsson",
    "email": "abs@gmail.com",
    "password": "abc123",
    "role": "user"
}

###

POST http://localhost:5000/api/login
Content-Type: application/json

{
    "userName": "test5",
    "firstName": "Maria",
    "lastName": "Norén",
    "email": "4",
    "password": "maria123",
    "role": "admin"
}

###

POST http://localhost:5000/api/post 
Content-Type: application/json

{
    "text": "Hello world3"
}

###

PUT http://localhost:5000/api/post/:id
Content-Type: application/json

{
    "_id": "60816ec3e7c77b55f1937759",
    "text": "Goodbye world"
}

###

PUT http://localhost:5000/api/user/:id
Content-Type: application/json

{
    "_id": "6081712183c493590a981f42",
    "role": "admin"
}

###

DELETE http://localhost:5000/api/user/:id
Content-Type: application/json

{
    "_id": "60816e34e7c77b55f1937757"
}

### 

DELETE http://localhost:5000/api/post/:id
Content-Type: application/json

{
    "_id": "60816e34e7c77b55f1937757"
}

###

DELETE http://localhost:5000/api/logout

